from tkinter import *
window = Tk()
window.geometry("6000x4000")
window.title("Interest Calculator")
window.configure(bg = "light green")
f1 = Frame(master = window, bg = "blue", bd = 20, width = 290, height = 300, relief = GROOVE)
l1 = Label(f1, text = "Simple interest", bg = "yellow", fg = "black", font= ("Times New Roman", 45))
l2 = Label(f1, text = "Principal amount", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e1 = Entry(f1, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
l3 = Label(f1, text = "Num. of years", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e2 = Entry(f1, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
l4 = Label(f1, text = "Rate(% p.a.)", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e3 = Entry(f1, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
def p1():
    p = float(e1.get())
    t = float(e2.get())
    r = float(e3.get())
    intr = p * t * (r/100)
    s = p + intr
    l9 = Label(window, text = f"Interest: {intr}, total money: {s}", bg = "light blue", fg = "black", font = ("Times New Roman", 25))
    l9.place(x = 50, y = 520)
    
btn1 = Button(f1, text = "Calculate Simple Interest", bg = "yellow", fg = "black", font = ("Times New Roman", 32), command = p1)

f2 = Frame(master = window, bg = "blue", bd = 20, width = 300, height = 300, relief = GROOVE)
l5 = Label(f2, text = "Compound interest", bg = "yellow", fg = "black", font= ("Times New Roman", 45))
l6 = Label(f2, text = "Principal amount", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e4 = Entry(f2, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
l7 = Label(f2, text = "Num. of years", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e5 = Entry(f2, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
l8 = Label(f2, text = "Rate(p.a. %)", bg = "blue", fg = "white", font= ("Times New Roman", 32))
e6 = Entry(f2, width = 20, bd = 5, bg = "light blue", fg = "black", font = ("Times New Roman", 32))
def p2():
    p = float(e4.get())
    t = float(e5.get())
    r = float(e6.get())
    intre = p * ((1 + (r/100)) ** t) - p
    intr2 = intre + p
    l10 = Label(window, text = f"Intrest: {intre}, Money: {intr2}", bg = "light blue", fg = "black", font = ("Times New Roman", 25))
    l10.place(x = 50, y = 920)
    
btn2 = Button(f2, text = "Calculate Compound Interest", bg = "yellow", fg = "black", font = ("Times New Roman", 32), command = p2)

f1.place(x = 10, y = 10)
f2.place(x = 500, y = 10)
l1.pack()
l2.pack()
e1.pack()
l3.pack()
e2.pack()
l4.pack()
e3.pack()                                   
btn1.pack()
l5.pack()                                                                                       
l6.pack()
e4.pack()
l7.pack()
e5.pack()
l8.pack()
e6.pack()
btn2.pack()
window.mainloop()